# Generated by Django 6.0.5 on 2026-06-03 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=20)),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('durum', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sofor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('ehliyet_no', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cikis_noktasi', models.CharField(max_length=100)),
                ('varis_noktasi', models.CharField(max_length=100)),
                ('tahmini_sure', models.IntegerField()),
                ('durum', models.CharField(max_length=30)),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojistik.arac')),
                ('sofor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojistik.sofor')),
            ],
        ),
    ]
